#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    line=$(dig "$2"."$1" +short)
    if [ -z "$line" ]; then
        echo "The subdomain $2 does not exist or has no A record"
    else
        echo "$2 $line" | awk '{print "The subdomain " $1 " is a A record and points to " $2}'
    fi
}

if [ "$#" -eq 1 ]; then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  domain_information "$1" "$2"
else
  echo "Usage: ./1-world_wide_web <domain> [subdomain]"
  exit 1
fi
