#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server to return "Hello World!" at the root URL

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
