#!/usr/bin/env bash
# Automating nginx configuration.

# Update the package list and install nginx
apt-get update
apt-get -y install nginx

# Create directory and files for the website
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to include the custom header
printf "server {
    listen 80;
    listen [::]:80 default_server;
    server_name _;
    
    add_header X-Served-By \$HOSTNAME;
    
    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    
    error_page 404 /404.html;
    location /404 {
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx to apply the changes
service nginx restart

