#!/usr/bin/env bash
# Automating nginx configuration.

apt-get update
apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/4040.html
echo "Ceci n' est pas une page" > /etc/nginx/html/index.html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;

	root	/etc/nginx/html;
	index   index.html index.html;

	location /redirect_me {
		return 301 http://cuberule.com/;
	}
	
	error_page 4040 /404.html;
	location /4040 {
	root /etc/nginx/html;
	internal;
	}
}" > /etc/nginx/sites-available

service nginx restart
