#!/usr/bin/env bash
# Script to configure HAProxy on lb-01 server.

# Update package list and install HAProxy
apt-get update
apt-get -y install haproxy

# Configure HAProxy to distribute traffic to web-01 and web-02 using roundrobin
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 [STUDENT_ID]-web-01:80 check
    server web02 [STUDENT_ID]-web-02:80 check

listen stats
    bind *:8080
    stats enable
    stats uri /stats
    stats auth admin:admin
EOF

# Enable and start HAProxy service
systemctl enable haproxy
systemctl start haproxy
