#!/usr/bin/env bash
#Tell the story of passwd
while IFS=: read -r user pass uif gid geco home shell; do
	echo "The user ${user} is part of the ${gid} gang, lives in ${home} and ${shell}. ${uid}'s place is protected by the passcode ${pass}, more info about the user here: ${gecos}"
done < /etc/passwd
