#!/usr/bin/env bash
#Displays information about the school file

if [ ! -e school ]; then
	echo "school file does not exists"
else
	echo "school file exist"
	if [ ! -s school ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f school ]; then
		echo "school is a regular file"
	fi
fi
