#!/usr/bin/env bash
# Fix this container so that Nginx is running the nginx user

sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80;listen 8080;/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
