#!/usr/bin/env bash

# Run Nginx as Nginx
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart
if ps aux | grep '[n]ginx' | awk '{print $1}' | grep -q '^nginx$'; then
	echo "Nginx is running as the nginx user."
else
	echo "Nginx is not running as the nginx user."
	exit 1
fi
if nc -z 0 8080; then
	echo "Nginx is listening on port 8080."
else
	echo "Nginx is not listening on port 8080."
	exit 1
fi
# pkill apache2
# sudo -u nginx service nginx restart
