#!/usr/bin/env bash
id nginx || sudo useradd --system --no-create-home --shell /usr/sbin/nologin nginx
grep '^user ' /etc/nginx/nginx.conf || exit 0
sudo sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /var/log/nginx /var/lib/nginx /etc/nginx
sudo chmod -R 755 /var/log/nginx /var/lib/nginx
sudo systemctl restart nginx
